### ISSUE TITLE
[BUG] 플레이중인 방에는 들어가지 못하게 한다.

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/Project18-B-Web-Duxit#117]
## 🚒 버그 설명
> 팀원이 이해할 수 있도록 자세하게 구체적으로 작성합니다. 담당자도 함께 할당해주세요.

1. 플레이 중인 방에서 새로고침하면 방에 들어가진다.
2. 그래서 카드를 1장씩만 받는다.

## ✔️ 기대하는 결과
> 구체적으로 어떤 결과가 나오게 수정해야 하는지 작성합니다.

END가 되지 않은 방은 못가게 한다.

## 🗒 참고자료
> 보여지는 에러인 경우 스크린샷도 함께 첨부합니다.

**Comment by Front-line-dev** [comment]
![image](https://user-images.githubusercontent.com/67293994/101111725-27875a00-361f-11eb-8ff8-871ad436db5b.png)
