### ISSUE TITLE
[BUG] teller sellect card scene에서 "가끔" 뒷면이 나옴

### ISSUE THREAD

**Issue by ramram1048** [boostcamp-2020/Project18-B-Web-Duxit#126]
## 💁 설명

![image](https://user-images.githubusercontent.com/48747221/101116021-a8e2ea80-3627-11eb-89ed-2598d029f0ca.png)

분명 앞면이었는데 갑자기 뒷면이 되있어요. 이유는 모르겠어요.

**Comment by Front-line-dev** [comment]
아마 0번 카드가 문제로 판명남
