### ISSUE TITLE
음성 채팅 버그

### ISSUE THREAD

**Issue by jinhyukoo** [boostcamp-2020/Project18-B-Web-Duxit#144]
## 💁 설명

현재 마이크 연결 버튼을 눌렀을 때 될 때도 있고 안 될 때도 있다. 새로 고침을 하면서 음성 채팅을 연결하면 연결은 되지만 초기에 이벤트가 제대로 발생하지 않는 버그가 있다. 원인을 분석하고 해결하도록 하자!

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [ ] 이벤트 바로 연결되게 수정하기

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 버튼을 누르지 않고 대기실에 들어오자마자 연결되게 하면 잘 되는 것을 확인했습니다. 버튼에 이벤트로 추가하면서 뭔가 문제가 생긴 것 같다는 느낌입니다... (정확하지는 않아요!)

**Comment by Front-line-dev** [comment]
아마도 제가 고친거 같아요
