### ISSUE TITLE
메인 페이지 - 대기실 코드 입력하기 기능 구현

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/Project18-B-Web-Duxit#15]
## 💁 설명

- 사용자가 <코드 입력하기> 버튼을 클릭했을 때 발생하는 기능 구현

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [ ] <코드 입력하기> 버튼 클릭 시 코드 입력하는 input와 입장 버튼이 생긴다.
- [ ] 방 코드 입력 시 유효한 코드인 경우 해당 방으로 이동
- [ ] 잘못된 코드 입력 시 input 창 하단에 에러 문구 렌더

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 유효한 경우 이동하게 하는 기능을 최우선적으로 구현한다.

**Comment by jinhyukoo** [comment]
프론트에서 작업은 끝나신것 같으니 close 할게요!
