### ISSUE TITLE
Teller Select ~ Player Waiting 시간을 서버에서 관리

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/Project18-B-Web-Duxit#161]
## 💁 설명

현재는 클라이언트에서 progress bar를 렌더링하는데 해당 시간을 서버에서 제공하고 클라이언트는 그것에 따라 관리

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [ ] 각 씬 별로 서버가 클라이언트에게 제한 시간을 준다.

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

**Comment by Front-line-dev** [comment]
지금은 서버에서 시간을 제공하는거로 바뀌긴 했는데 끝나는 시간의 타임스탬프를 주는거 대신에 시간을 int 형식으로 넘겨주면 안 될까요?

**Comment by sbyeol3** [comment]
@Front-line-dev 좋습니다~ 낼 수정할게요~~

**Comment by Front-line-dev** [comment]
결국은 그냥 Date() 객체 (string)을 넘겨주는걸로 결론 난거 같네요
