### ISSUE TITLE
EndTime에 대한 타임존 영향

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/Project18-B-Web-Duxit#172]
## 💁 설명

서버에서 시간을 보내주는데 다른 타임존이라면 어떻게 작동할까?
문제가 발생한다면 대응해보자

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [ ] 여러 타임존에서 사용하는 클라이언트를 대응하기

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

**Comment by Front-line-dev** [comment]
제가 생각했던건 끝나는 시간 데이터를 보내기 보다 60000 같은 데이터를 보내는게 낫다고 생각했어요. 물론 이것도 유저마다 RTT가 달라서 조금 오차가 있겠지만 아마 100ms 이내 범위이지 않을까요?

**Comment by ramram1048** [comment]
잘된다고 하십니다 by 민성님.
