### ISSUE TITLE
카드 디폴트 토픽 JSON 작성하기

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/Project18-B-Web-Duxit#173]
## 💁 설명

제가 임의로 설정합니다
@Front-line-dev 21 ~ 70
@ramram1048 71 ~ 120
@jinhyukoo 121 ~ 170
@sbyeol3 1~20 171 ~ 206

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [ ] cardTopic.json 작성하기~
- [ ] 없는 번호를 찾자..?

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 너무 쉽게 쓰지는 말기!

**Comment by jinhyukoo** [comment]
작성 완료! 슬랙에 올렸습니당~

**Comment by Front-line-dev** [comment]
작성 완료 했습니다! 해람님도 작성 완료 했습니다. 저희가 한거 머지 했습니다~

**Comment by sbyeol3** [comment]
토픽 끝!
