### ISSUE TITLE
[BUG] Discussion에 늦게 들어온 유저가 있으면 ProgressBar 초기화되는 현상

### ISSUE THREAD

**Issue by jinhyukoo** [boostcamp-2020/Project18-B-Web-Duxit#179]
## 🚒 버그 설명
> 애니메이션이 끝나는 시점에서 emit을 하다보니 애니메이션을 늦게 보는 유저가 있으면 기존 유저들의 ProgressBar가 초기화 되는 현상이 있습니다. 시간은 잘 맞으나 가득 채워지면서 다시 타이머가 시작됩니다 ㅠㅠ

## ✔️ 기대하는 결과
> ProgressBar에 Parameter로 전체 길이를 줌으로써 해결 할 수 있을듯 합니다. 더 좋은 방법이 있으면 그걸로 해도 좋아요~

**Comment by Front-line-dev** [comment]
아마 서버 코드가 잘못되어있어서 그런걸거에요. 지금은 고쳐졌을겁니다
