### ISSUE TITLE
프론트엔드에서 소켓 코드 관리에 대해 논의를 원해요.

### ISSUE THREAD

**Issue by ramram1048** [boostcamp-2020/Project18-B-Web-Duxit#188]
저희가 소켓 코드를 각 scene 안에 파일을 만들고 scene을 렌더할 때마다 setup을 실행하고 있는데 이게 문제가 될 것 같습니다.

### 문제 1: event listener가 점점 쌓임.
지금 라운드 1만 테스트하고있으니 문제를 발견하지 못한건데 라운드 2가 되면 씬이 새로 생성될 때마다 socket event가 하나 더 생기게되서 같은 이벤트 이름에 대해 2개의 리스너가 반응하고 콜백함수가 2번 실행될 것이 예상됩니다. n라운드가 되면 n번 실행되겠죠. 

### 문제 2: 자기 scene render에 필요한 값을 이전 scene event에서 받아야됨.
scene A, B가 있을때 A->B라고 하면, 지금은 B를 render하는데 필요한 args를 A에서 받아야되는 구조입니다. 
예를 들어서 game end scene을 구현할 때 'game over' event를 받아서 거기 있는 args를 써야되는데, `gameEnd` 폴더에 `socket.js` 파일을 만들어서 'game over' 이벤트를 on하면... 얘를 어디다 초기화해야되지? game end에다 초기화할 수 있나요? 얘는 아직 렌더링이 안됐는데... 그러면 그 이전 scene인 score board scene에다 초기화하면 되겠다. 근데 이러면 얘는 소켓 명세랑은 다른 것 같은데...
지금의 구조로는 작성한 소켓 명세를 바꾸거나, 폴더 구조를 어색하게 가져가거나 둘중 하나를 택해야할 것 같아요.

-----

이를 위한 해결책으로 backend에서 소켓 코드 다루는 것처럼 socket 폴더를 따로 두고 거기서 통합적으로 관리하는게 어떨까 합니다. 매번 scene instance를 생성할 때마다 event listen을 하는게 아니라 그냥 어플리케이션 키면 모든 event를 한번만 listen하게 하는거죠.

문제의 발생 여지를 줄이기 위해 각 이벤트의 콜백함수에서 `SceneManager.isCurrentScene`같은 메소드를 활용해 조건을 걸어두면 크게 문제될 일도 없을 것 같습니다.

일부 이벤트 콜백함수는 특정 scene의 component를 참조해야되서 scene이 새로 생성될 때마다 새로 정의해줘야 되는 경우가 있는데요. 그럴때는 `socket.off`를 활용합시다. <https://socket.io/docs/v3/listening-to-events/#socket-off-eventName-listener>
새로 정의한 scene에서는 wrapup 메소드에 `socket.off`를 사용해줘서 이벤트를 꺼줄 수 있을 것 같습니다.

**Comment by jinhyukoo** [comment]
굉장히 좋은 생각입니다! 미리 생각을 해봤어야 하는 문제였는데 미처 생각하지 못했네요...!
