### ISSUE TITLE
scss 리팩토링 하기

### ISSUE THREAD

**Issue by jinhyukoo** [boostcamp-2020/Project18-B-Web-Duxit#193]
## 💁 설명

중복되는 코드 줄이기 및 중복 import 막기 등등 여러가지...

![image](https://user-images.githubusercontent.com/46101366/101850715-afc8aa80-3b9d-11eb-934b-c1b20df959bc.png)

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [ ] 중복되는 코드 줄이기
- [ ] 여러번 import 되는 문제 막기

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

**Comment by sbyeol3** [comment]
#86 랑 동일한 이슈이므로 close합니다.
