### ISSUE TITLE
클립보드 복사 버튼 눌렀을때 피드백 넣기

### ISSUE THREAD

**Issue by ramram1048** [boostcamp-2020/Project18-B-Web-Duxit#194]
## 💁 설명

waitingRoom의 클립보드 복사 버튼을 눌렀을 때 복사가 잘 됐는지 안됐는지에 대한 반응이 없어서 이게 잘 된건가 쳐봐야 아는 불편함이 있네요. 성공/실패에 따라 시각적인 피드백을 넣어줍시다.

**Comment by jinhyukoo** [comment]
저도 같은 생각했어요! 화면 중앙에 `코드가 복사되었습니다.` 이런 메세지가 작게 2초 정도 나타났다 사라지면 괜찮지 않을까 싶네요! 그리고 호눅스님이 말씀하셨던 것 처럼 에러 메세지도 상황에 맞게 적절한 코드가 보여지면 좋겠네요! 요건 이슈로 파겠슴다 ㅎㅎ
