### ISSUE TITLE
백엔드 리팩토링

### ISSUE THREAD

**Issue by Front-line-dev** [boostcamp-2020/Project18-B-Web-Duxit#196]
## 💁 설명

백엔드 코드 리팩토링
- Game이 너무 비대해지는 문제
- 서버가 가끔씩 죽는 문제
- 중복된 코드가 있는 문제
- 플레이어가 나가면 에러가 발생하는 문제

## 📑 체크리스트

- [ ] Game.js 리팩토링
- [ ] 서버가 안 죽음
- [ ] 중복된 코드 제거
- [ ] 플레이어가 나가면 해당 게임에 있는 모든 플레이어들은 강제로 나가짐

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

**Comment by Front-line-dev** [comment]
가장 먼저, 리팩토링 후 Game이 어떤 구조를 가져야 할지 생각해봤다.
현재 Game의 가장 큰 문제는 메소드가 너무 많다는것이다.

1. 서비스 코드 분리
service 폴더를 만들어서 Game의 메소드에 해당하는 코드를 작성한다. 게임 스테이지에 해당하는 이름으로 만들어서 파일을 나누면 그럭저럭 메소드를 헤매지 않고 찾을 수 있다. 하지만 game.doSth() 같이 쓸 수 없고 doSth(game) 처럼 써야한다는게 좀 걸린다

2. 믹스인 기법
https://velog.io/@moggy/Javascript-%EB%AF%B9%EC%8A%A4%EC%9D%B8-%EA%B8%B0%EB%B2%95Mixin-technique
클래스의 메소드를 여러 파일에서 정의 할 수 있다. 위에서 말한 코드의 작성방법을 해결 할 수 있다. 하지만 중복 코드가 발생할 수 있는 문제점이 있다

3. 아토믹 디자인
https://ui.toast.com/weekly-pick/ko_20200213
가장 작은 단위의 행동을 원자, 행동들을 모은 기능을 분자... 이런식으로 공통된 코드를 사용하는 메소드를 줄일 수 있을거 같다

**Comment by ramram1048** [comment]
1. 아래처럼 작성할 수 있지않을까요 ????
```
// tellerSelect.js
export function submitTellerCard {
  // do something...
}

// game.js
import { submitTellerCard } from './tellerSelect';

const Game = class {
  constructor() {
    this.submitTellerCard = submitTellerCard.bind(this);
  }
}
```

2 믹스인도 나쁘진않을것같은데 저희 문제점을 위해 필요한 기술은 아닌 것 같아요. 저희 문제점에 믹스인을 활용할 수는 있지만, 믹스인이 사용되는 이유에 부합하지는 않는다는 느낌? 
많은 믹스인을 사용할때 lodash의 compose를 사용하는게 좋다는데 직접 구현할 수도 있을 것 같아요.

3 아토믹 디자인기법은 어떻게 클래스에 적용시킬수있는건지 잘 감이안오네요...

**Comment by Front-line-dev** [comment]
저하고 똑같은 생각을 하셨군요 ㅋㅋ 결국은 저렇게 구현 했습니다. 아토믹 디자인 기법은 간단한 메소드 몇개를 섞어서 복잡한 기능을 하는 메소드를 만들어 보려고 합니다
