### ISSUE TITLE
ncloud 서버 설정

### ISSUE THREAD

**Issue by ramram1048** [boostcamp-2020/Project18-B-Web-Duxit#2]
## 💁 설명

nCloud 서버 설정합니다.

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [x] ssh 키설정
- [x] 노드 설치
- [x] git clone

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 외부에서 DB root로 접속하지 못하게 권한 설정

**Comment by sbyeol3** [comment]
#### IP 주소 : 49.50.167.167
