### ISSUE TITLE
[Vote Scene] 강제 투표 기능 구현

### ISSUE THREAD

**Issue by jinhyukoo** [boostcamp-2020/Project18-B-Web-Duxit#207]
## 💁 설명

유저가 시간 내에 투표를 하지 않았을 경우 강제로 투표가 진행되게 한다.
강제 투표는 랜덤이다.

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [ ] end vote가 될 때까지 투표값이 null일 경우 임의의 값으로 채워주자.

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

**Comment by Front-line-dev** [comment]
일단 서버쪽에서는 구현 했습니다~

**Comment by jinhyukoo** [comment]
서버쪽에서 구현 됐으면 된 것 같습니당~
