### ISSUE TITLE
[BUG] 홈페이지에서 대기실 코드 입력하기 버튼 커서 포인터 아님

### ISSUE THREAD

**Issue by Front-line-dev** [boostcamp-2020/Project18-B-Web-Duxit#270]
## 🚒 버그 설명

홈페이지에서 대기실 코드 입력하기 버튼 커서 포인터 아님

## ✔️ 기대하는 결과
> 구체적으로 어떤 결과가 나오게 수정해야 하는지 작성합니다.

## 🗒 참고자료
> 보여지는 에러인 경우 스크린샷도 함께 첨부합니다.

**Comment by jinhyukoo** [comment]
그리고 대기실 코드 입력하기 누르면 그 자리에 바로 코드 인풋창이랑 입력 버튼이 나왔는데 지금은 위로 밀리면서 생기네요. 수정 하면 좋을듯!?
