### ISSUE TITLE
[BUG] 카드 개수가 다른 경우가 가~끔 생김

### ISSUE THREAD

**Issue by ramram1048** [boostcamp-2020/Project18-B-Web-Duxit#287]
![image](https://user-images.githubusercontent.com/48747221/102562239-0001b880-411a-11eb-98a1-6e10d5799abf.png)

믹스카드에서 카드 모여있을때 카드 개수를 맞춰주는게 필요할지도 ??

**Comment by Front-line-dev** [comment]
가~끔이라기에는 은근히 자주 보였고 게임 진행에 어느정도 치명적이라서 주말에 수정합니다
