### ISSUE TITLE
좌표 계산 방식 ratio VS transform(zoom)

### ISSUE THREAD

**Issue by Front-line-dev** [boostcamp-2020/Project18-B-Web-Duxit#34]
## 💁 설명

(x,y) 좌표에 카드를 두고 싶다. 문제는 사용자의 환경에 따라 화면의 크기와 비율이 바뀐다는 점이다.
이 때, 비율 방식과 transform(줌) 방식을 사용 가능하다

### 비율 방식 장점
- 비율 방식은 (50%, 30%) 이런식으로 가로의 50%와 세로의 30%를 찾아서 오브젝트를 배치할 수 있다
- 어떤 비율이나 해상도에서도 깨지지 않는 화면을 보여줄 수 있다

### 비율 방식 단점
- 사용자의 화면비율에 따라 보이는 화면이 다르다. 여러가지 비율을 고려해야 한다.
- 오브젝트가 움직이는것을 transition으로 처리하는데, 윈도우의 크기가 바뀔때에도 렌더링을 다시 해야하기 때문에 애니메이션이 꼬일 수 있다.

> 비율 설정을 잘 못해서 카드가 엄청나게 겹치는 경우
![image](https://user-images.githubusercontent.com/67293994/99970692-8c50e200-2ddf-11eb-9fdb-9f2d01959659.png)

### 줌 방식 장점
- 줌 방식은 하나의 Div를 만들어 두고 그 Div를 확대, 축소 해서 화면을 표현한다. (100, 200)
- 어떤 비율이나 해상도에서도 같은 화면을 보여줄 수 있다.

### 줌 방식 단점
- 같은 비율을 유지해야하기 때문에 설정된 비율과 다르면 잘리는 부분 혹은 빈 부분이 생긴다.
- 프로그레스바와 같은 UI가 있기에 잘리는 선택은 하지 못해서 사실상 빈 공간이 생기는 방식이라고 보면 된다.

> 화면 비율이 맞지 않아서 엄청나게 빈 공간이 생기는 경우
![image](https://user-images.githubusercontent.com/67293994/99970550-56abf900-2ddf-11eb-9409-d590e6c4a31b.png)

## 🚧 주의 사항

카드가 손에 보이는 연출이 있기 때문에 줌 방식을 채택 할 경우 의도한 UX가 안 나올 수 있음
그래서 개인적으로 비율 방식을 추천

**Comment by jinhyukoo** [comment]
역시 민성님은 그림에 재능이 있으셨던 것입니다... 너무 잘 표현하셨는데요!? ㅋㅋㅋㅋㅋ 좋은 고민 나눠주셔서 감사해요!

**Comment by Front-line-dev** [comment]
지금 다시 생각해보니 zoom 방식도 너무 끌리네요. 제가 제 마음을 모르겠어요

**Comment by ramram1048** [comment]
비율이요~~~

**Comment by ramram1048** [comment]
### 비율
- transition이 아닌 keyframe animation으로하면 애니메이션이 다시 재생되버리는 버그가 없다~~~

### 줌
- 모바일 만들기 되게 쉬울것같다~~
- 개발 자체의 난이도도 되게 쉬울것같다~~

**Comment by sbyeol3** [comment]
#### 모든 오브젝트를 fixed 또는 relative 한 것으로 위치 관리를 할 것인가?
- 개발을 할 때 고려할 것들이 적어진다. 섞어서 하면 개발할 때마다 이 오브젝트의 특성을 생각한다

#### 오브젝트의 특성마다 섞어서 위치 관리를 할 것인가?
- flexible하게 하자 생각보다 오브젝트는 많지 않다.

=> 오브젝트가 많지 않으니까 어떤 방법이든 괜찮을 것 같다. 일단 fixed로 가보자~
