### ISSUE TITLE
ESLint와 Prettier 설정

### ISSUE THREAD

**Issue by Front-line-dev** [boostcamp-2020/Project18-B-Web-Duxit#39]
### VSCode에서 저장시 자동 바꿔주기 기능을 사용하기 위한 준비

1. `npm i -D eslint prettier eslint-plugin-prettier eslint-config-prettier` 글로벌로 설치도 가능하긴 하다
2. VSCode 확장앱 [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) 설치
3. VSCode Workspace 설정 (한 사람이 하고 Git에 올리면 됨)
![image](https://user-images.githubusercontent.com/67293994/100123442-db6d4480-2ebd-11eb-9937-9596f7d071ed.png)
![image](https://user-images.githubusercontent.com/67293994/100123542-f6d84f80-2ebd-11eb-86c0-c59081be6ecf.png)
```
{
  // Set the default
  "editor.formatOnSave": false,
  // Enable per-language
  "[javascript]": {
    "editor.formatOnSave": true
  },
  "editor.codeActionsOnSave": {
    // For ESLint
    "source.fixAll.eslint": true
  }
}
```
이 작업을 하면 .vscode 폴더에 settings.json이 생성되며 Git에 올리면 모든 사람들이 받아서 쓸 수 있다.

4. 환경설정 만들기 (이 작업도 한 사람이 하면 된다)
- `npx eslint --init` 하고 질문에 대답한다. (포맷은 JSON으로 한다)
- prettier와 연결 시켜주기 위해 `.eslintrc.json`에 다음의 옵션을 추가한다
```
// 복붙하지 말고 중복된 부분을 찾아서 잘 이어줘야한다
{
  "plugins": ["prettier"],
  "extends": ["eslint:recommended", "plugin:prettier/recommended"],
  "rules": {
    "prettier/prettier": "error"
  }
}
```
- `.prettierrc.json`도 위와 같이 만들 수 있으나 미리 설정 된 파일을 수정하는게 더 빠르다
```
{
  "printWidth": 100,
  "tabWidth": 2,
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": true,
  "semi": true,
  "useTabs": false,
  "arrowParens": "avoid",
  "endOfLine": "auto"
}
```

## 📑 체크리스트

ESLint와 Prettier를 둘 다 사용하는 이유?
- 두개의 역할이 겹치는 부분도 있지만 안 겹치는 부분도 있어서

VSCode 확장앱을 설치하는 이유?
- 확장앱은 node_modules 폴더에서 eslint 모듈을 찾아서 VSCode와 연결시켜준다

## 🚧 주의 사항

![image](https://user-images.githubusercontent.com/67293994/100127142-28531a00-2ec2-11eb-97fd-30eb6b9a65d7.png)

## 참고한 사이트

https://code.visualstudio.com/docs/editor/multi-root-workspaces

https://velog.io/@recordboy/ESLint-Prettier-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0

**Comment by Front-line-dev** [comment]
너무 피곤해서 직접 이걸 프로젝트에 적용하고 PR날리는건 내일 할게요

**Comment by ramram1048** [comment]
https://github.com/boostcamp-2020/Project18-B-Web-Duxit/pull/4#issue-524247791

여기에 lint관련해서도 정리 많이 해뒀어요!!
그리구 오전 회의할때 말씀을 따로 못드렸는데 vscode 설정파일은 PR로날리거나 하지않으시고 그냥 개인별로 가지고있어도 괜찮다고 생각됩니다
