### ISSUE TITLE
음성채팅은 뭐로할지 기술 스택 고민??

### ISSUE THREAD

**Issue by ramram1048** [boostcamp-2020/Project18-B-Web-Duxit#6]
## 💁 설명

기술스택 생각 안해본것같은데 정해보면 좋을것같네요~
일단 Web Audio 던져봅니다~ <https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API>

**Comment by Front-line-dev** [comment]
저도 좀 공부해봐야겠네요

**Comment by Front-line-dev** [comment]
음성 데이터를 전달하는 방법은 여러가지가 있지만 보통 p2p 방식으로 구현한다고 하네요. webRTC를 이용하고 우리가 바닐라로 만들 수도 있지만 좋은 라이브러리들이 많네요. 여기를 참고 했습니다 https://stackoverflow.com/questions/29140037/implementing-audio-chat-with-socket-io-and-nodejs

**Comment by sbyeol3** [comment]
WebRTC로 결정!

**Comment by Front-line-dev** [comment]
만약 시간이 남으면 바닐라로 구현. 시간이 없으면 라이브러리를 사용

**Comment by ramram1048** [comment]
WebAudio는 오디오를 웹상에서 재생시키거나 편집하는느낌? buffer로 저장할수있는건 맞는데 전송하기에는 다른 socket.io같은 툴을 써야할것만같음. 음성채팅 관련 검색하기에도 WebRTC가 더 편해보여서 이걸로 가요
