### ISSUE TITLE
배포 서버에서 sudo 사용 시 비밀번호를 물어보는 문제

### ISSUE THREAD

**Issue by ramram1048** [boostcamp-2020/Project18-B-Web-Duxit#62]
## 💁 설명

ncloud 배포 서버에서 sudo 사용 시 비밀번호를 물어보는 문제.

배포 시 프론트엔드 빌드 결과물을 nginx 폴더에 넣는 과정에서
NGINX 폴더가 root 폴더에 있다보니 `cp` 명령어 사용시 root권한이 필요한데 이때 sudo를 치면 비밀번호를 물어보고 있습니다
수동 배포를한다면 그냥 비밀번호 치면되는데 자동 배포를 하려하면 root 비밀번호를 GitHub Secret같은곳에 넣어둬야된다거나... 여러 보안 취약점이 발생한다고 느껴집니다~~

1줄요약: 자동배포 하려면 비밀번호를 물어보지 않도록 잘 설정이 되어있어야 할 듯 합니다~~

**Comment by ramram1048** [comment]
구글에 visudo not workinig으로 검색해서 글좀보다가 해결했습니다.
visudo 파일에서 얘네 두개가 붙어있어야되는게아니라 1라인 떨어져있어야된다고 하네요. 붙어있었습니다.
![image](https://user-images.githubusercontent.com/48747221/100493078-da1a7100-3176-11eb-9a5b-80c1b3a5b0fe.png)

참 어려운 친구네요...

**Comment by Front-line-dev** [comment]
정말 어이가 없네요... 발견하셔서 해결하셨다니 정말 다행입니다

**Comment by sbyeol3** [comment]
롸... 근데 예전에는 또 됐거든요..? 뭐지뭐지 개인프로젝트할 때는 저렇게도 되던데 휴

**Comment by ramram1048** [comment]
알고보니 해결된게 아니었네요

**Comment by ramram1048** [comment]
그룹 문제였네요~ duxit 유저가 그룹 duxit, sudo 그룹에 들어있었는데
sudo그룹의 권한이 visudo에 적용되있어서 duxit 유저의 권한이 sudo그룹 권한에 덮어씌워져서 적용이 안 되는 것이었습니다.
duxit 유저를 sudo그룹에서 제외하는 것으로 해결했습니다.
