### ISSUE TITLE
음성채팅을 위한 PeerJS 서버 만들기~~

### ISSUE THREAD

**Issue by ramram1048** [boostcamp-2020/Project18-B-Web-Duxit#66]
## 💁 설명

진혁님의 PeerJS를 위한 서버를 만들어봅시다 ~~
기존 backend 코드에 삽입이 가능할 것 같으니 그것도 참고합시다 ~~

참고자료: <https://github.com/peers/peerjs-server#combining-with-existing-express-app>

**Comment by Front-line-dev** [comment]
일단 peerjs의 stun서버를 사용하기로 결정. 백엔드에서도 https가 적용되었기때문에 나중에 시도해볼만함
