### ISSUE TITLE
로그용 데이터베이스 탐색

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/Project18-B-Web-Duxit#7]
## 💁 설명

일정하게 구조화된 데이터를 쌓아야 하는 프로젝트가 아니기 때문에
로그를 쌓을 수 있는 데이터베이스를 찾아서 정해봅시다!

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [x] 로그 쌓기에 적합한 DB를 찾아봅니다.

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 관련 자료는 슬랙이나 코멘트로 달아주세요

**Comment by Front-line-dev** [comment]
인터넷에 찾아보니 파일시스템 기반 로거 node 패키지를 다들 얘기합니다. 유명한거로는 winston이 있고 다른 건 morgan이 있는데 express-generator로 생성한 우리 프로젝트에는 morgan이 이미 설치가 되어 있더군요. 다만 morgan은 router middleware로 socket.io에는 적용을 못 할거 같아요. winston한번 써 볼까요?

**Comment by sbyeol3** [comment]
저도 찾아보니 `winston `이 제일 많이 나오는 것 같습니다~

- [참고자료1](https://dololak.tistory.com/126)
- [참고자료2](https://velog.io/@ash/Node.js-%EC%84%9C%EB%B2%84%EC%97%90-logging-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-winston-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0)
