### ISSUE TITLE
닉네임 12글자 제한 두기

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/Project18-B-Web-Duxit#72]
## 💁 설명

레이아웃 width 제한으로 닉네임이 길면 레이아웃 깨짐

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [x] 닉네임 수동변경 시 12글자 이하로 할 수 있게 추가

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

**Comment by ramram1048** [comment]
동의합니다.
